---

- name: Ensure config path
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ any_sync_node_user }}"
    group: "{{ any_sync_node_group }}"
  with_items:
    - "{{ any_sync_node_config_path }}"
    - "{{ any_sync_node_networkStorePath }}"

- name: Copy config file
  template:
    src: config.yml.j2
    dest: "{{ any_sync_node_config_path }}/config.yml"
  notify: Restart any-sync-node

- name: Copy systemd init file
  template:
    src: service.j2
    dest: /etc/systemd/system/any-sync-node.service
  notify: Restart any-sync-node