---
- name: Deploy any-sync-coordinator
  hosts: any_sync_coordinator
  become: true
  roles:
    - any_sync_coordinator

- name: Deploy any-sync-node
  hosts: any_sync_node
  become: true
  roles:
    - any_sync_node

- name: Deploy any-sync-consensusnode
  hosts: any_sync_consensusnode
  become: true
  roles:
    - any_sync_consensusnode

- name: Deploy any-sync-filenode
  hosts: any_sync_filenode
  become: true
  roles:
    - any_sync_filenode
