---
# user and group that the any_sync_coordinator service will run as
any_sync_coordinator_user: any_sync_coordinator
any_sync_coordinator_group: any_sync_coordinator

any_sync_coordinator_version: 0.3.0
any_sync_coordinator_release_system: x86_64 # aarch64.rpm x86_64.rpm amd64.deb arm64.deb
any_sync_coordinator_release_name_rhel: "any-sync-coordinator-{{ any_sync_coordinator_version }}-1.{{ any_sync_coordinator_release_system }}.rpm"
any_sync_coordinator_download_url_rhel: "https://github.com/anyproto/any-sync-coordinator/releases/download/v{{ any_sync_coordinator_version}}/{{ any_sync_coordinator_release_name_rhel }}"

any_sync_coordinator_release_name_debian: "any-sync-coordinator_{{ any_sync_coordinator_version }}_{{ any_sync_coordinator_release_system }}.deb"
any_sync_coordinator_download_url_debian: "https://github.com/anyproto/any-sync-coordinator/releases/download/v{{ any_sync_coordinator_version}}/{{ any_sync_coordinator_release_name_debian }}"

# any sync coordinator configuration
# see: https://github.com/anyproto/any-sync-coordinator/blob/main/etc/any-sync-coordinator.yml
any_sync_coordinator_config_path: /etc/any-sync-coordinator
any_sync_coordinator_networkStorePath: /var/lib/any-sync-coordinator/networkStore
any_sync_coordinator_config:
  cafeApi:
    url: "https://<login:pass>@cafe1.anytype.io"
  drpc:
    stream:
      maxMsgSizeMb: 256
      timeoutMilliseconds: 1000
  fileLimit:
    limitAlphaUsers: 10737418240
    limitDefault: 1073741824
    limitNightlyUsers: 53687091200
  log:
    defaultLevel: ''
    namedLevels: {}
    production: false
  metric:
    addr: 0.0.0.0:8000
  mongo:
    connect: mongodb://any-sync-coordinator-db1:27017,any-sync-coordinator-db2:27017,any-sync-coordinator-db3:27017
    database: coordinator
    log: log
    spaces: spaces
  spaceStatus:
    deletionPeriodDays: 30
    runSeconds: 20
  yamux:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:443"
    writeTimeoutSec: 10
  quic:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:5430"
    writeTimeoutSec: 10
  networkStorePath: "{{ any_sync_coordinator_networkStorePath }}"
