---
# user and group that the any_sync_filenode service will run as
any_sync_filenode_user: any-sync-filenode
any_sync_filenode_group: any-sync-filenode

any_sync_filenode_version: 0.4.1
any_sync_filenode_release_system: x86_64 # aarch64.rpm x86_64.rpm amd64.deb arm64.deb
any_sync_filenode_release_name_rhel: "any-sync-filenode-{{ any_sync_filenode_version }}-1.{{ any_sync_filenode_release_system }}.rpm"
any_sync_filenode_download_url_rhel: "https://github.com/anyproto/any-sync-filenode/releases/download/v{{ any_sync_filenode_version}}/{{ any_sync_filenode_release_name_rhel }}"

any_sync_filenode_release_name_debian: "any-sync-filenode_{{ any_sync_filenode_version }}_{{ any_sync_filenode_release_system }}.deb"
any_sync_filenode_download_url_debian: "https://github.com/anyproto/any-sync-filenode/releases/download/v{{ any_sync_filenode_version}}/{{ any_sync_filenode_release_name_debian }}"

# any sync filenode configuration
# see: https://github.com/anyproto/any-sync-filenode/blob/main/etc/any-sync-filenode.yml
any_sync_filenode_config_path: /etc/any-sync-filenode
any_sync_filenode_networkStorePath: /var/lib/any-sync-filenode/networkStore
any_sync_filenode_aws_access: CHANGE_ME
any_sync_filenode_aws_secret_access: CHANGE_ME
any_sync_filenode_config:
  drpc:
    stream:
      maxMsgSizeMb: 256
      timeoutMilliseconds: 1000
  log:
    defaultLevel: ''
    namedLevels: {}
    production: false
  metric:
    addr: 0.0.0.0:8000
  redis:
    isCluster: true
    # example of redis instances initialization
    url: redis://any-sync-redis1:6379?dial_timeout=3&read_timeout=6s&addr=any-sync-redis1:6380&addr=any-sync-redis2:6379&addr=any-sync-redis2:6380&addr=any-sync-redis3:6379&addr=any-sync-redis3:6380
  s3Store:
    bucket: filenode
    maxThreads: 16
    profile: default
    region: eu-central-2
  yamux:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:443"
    writeTimeoutSec: 10
  quic:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:5430"
    writeTimeoutSec: 10
  networkStorePath: "{{ any_sync_filenode_networkStorePath }}"
