---
# user and group that the any_sync_filenode service will run as
any_sync_filenode_user: any-sync-filenode
any_sync_filenode_group: any-sync-filenode

any_sync_filenode_version: 0.5.4
any_sync_filenode_release_system: amd64 # aarch64.rpm x86_64.rpm amd64.deb arm64.deb
any_sync_filenode_release_name_rhel: "any-sync-filenode-{{ any_sync_filenode_version }}-1.{{ any_sync_filenode_release_system }}.rpm"
any_sync_filenode_download_url_rhel: "https://github.com/anyproto/any-sync-filenode/releases/download/v{{ any_sync_filenode_version}}/{{ any_sync_filenode_release_name_rhel }}"

any_sync_filenode_release_name_debian: "any-sync-filenode_{{ any_sync_filenode_version }}_{{ any_sync_filenode_release_system }}.deb"
any_sync_filenode_download_url_debian: "https://github.com/anyproto/any-sync-filenode/releases/download/v{{ any_sync_filenode_version}}/{{ any_sync_filenode_release_name_debian }}"


# any sync filenode configuration
# see: https://github.com/anyproto/any-sync-filenode/blob/main/etc/any-sync-filenode.yml
any_sync_filenode_config_path: /etc/any-sync-filenode
any_sync_filenode_networkStorePath: /var/lib/any-sync-filenode/networkStore

# s3 integration
any_sync_filenode_s3_access: accesskey
any_sync_filenode_s3_secret_access: secretaccesskey
any_sync_filenode_s3_bucket: s3-bucket

any_sync_filenode_config:
  drpc:
    stream:
      maxMsgSizeMb: 256
      timeoutMilliseconds: 1000

  metric:
    addr: 0.0.0.0:8000

  log:
    defaultLevel: ''
    namedLevels: {}
    production: false
  networkStorePath: "{{ any_sync_filenode_networkStorePath }}"

  redis:
    # isCluster: true
    # url: redis://any-sync-redis1:6379?dial_timeout=3&read_timeout=6s&addr=any-sync-redis1:6380&addr=any-sync-redis2:6379&addr=any-sync-redis2:6380&addr=any-sync-redis3:6379&addr=any-sync-redis3:6380
    isCluster: false
    url: "redis://{{ hostvars['redis'].ansible_host }}:6379?dial_timeout=3&read_timeout=6s"

  s3Store:
    bucket: "{{ any_sync_filenode_s3_bucket }}"
    indexBucket: "{{ any_sync_filenode_s3_bucket }}"
    maxThreads: 16
    profile: default
    region: us-east-1
    endpoint: http://minio.host:9000 # set for self-hosted S3 Object Storage
    forcePathStyle: true             # set for self-hosted S3 Object Storage

  yamux:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:{{ any_type_yamux_port }}"
    writeTimeoutSec: 10

  quic:
    dialTimeoutSec: 10
    listenAddrs:
    - "{{ ansible_host }}:{{ any_sync_quic_port }}"
    writeTimeoutSec: 10
