---

- name: Copy config file
  template:
    src: config.yml.j2
    dest: "{{ any_sync_consensusnode_config_path }}/config.yml"
  notify: Restart any-sync-consensusnode

- name: Copy systemd init file
  template:
    src: service.j2
    dest: /etc/systemd/system/any-sync-consensusnode.service
  notify: Restart any-sync-consensusnode
