on:
  push:
    tags:
      - '*.*.*'

name: Publish release on GH and Ansible Galaxy

permissions: write-all

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Update version for galaxy
        run: |
          sed -i "s/%VERSION%/${{ github.ref_name }}/g" galaxy.yml

      - name: Trigger a new import on Galaxy.
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} ./mighty_sponge-any_sync-${{ github.ref_name }}.tar.gz

      - name: Create GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
